---
title: "Filtrado Lecturas Hospedador"
author: "Samuel Piquer-Esteban"
date: "Última modificación `r format(Sys.time(), '%d %B %Y')`"
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
---

<div style="text-align: justify">

\newpage

#1. Eliminar lecturas de organismos host y posibles contaminantes

Lo que vamos a hacer es alinear las lecturas frente a genomas de posibles contaminantes/host de referencia usando Bowtie2(Langmead & Salzberg, 2012). La elección de esta herramienta para eliminar contaminantes se eligió en base a los resultados de Bush et al, 2020.

Cuando trabajamos con muestras asociadas a un organismo host es recomendable filtrar aquellas lecturas que puedan pertenecer a este organismo. También hay que tener en cuenta que toda muestra puede tener una cierta contaminación humana (ya sea por que es el host de las muestras estudiadas o por la propia manipulación humana de las muestras). Además, en el caso de muestras secuencias con la tecnología Illumina es posible detectar cierta contaminación del fago Phix que se utiliza como control (Mukherjee et al., 2015).

#1.1. Descarga de los correspondientes genomas

#1.1.1. Descarga del Genoma de Humano 38.p13

Se descargó la versión 38.p14 del genoma humano de RefSeq (GCF_000001405.40_GRCh38.p14_genomic.fna.gz). Además, en la versión anterior 38.p13 atendiendo a la advertencia de contaminación con la secuencia de Acidithiobacillus thiooxidans en Steinegger M. & Salzberg S. L. (2020) para la región 169919-188315 del Alternative scaffold NT_187580.1 del genoma humano, se decidió enmascarar esta región usando la herramienta bedtools(v2.29.2)(Quinlan & Hall, 2010). En la última versión ya no hay rastro de esta secuencia para comprobarlo se hizo un blast usando como query la secuencia NT_187580.1	169919-188315. Se hicieron 2 blast: uno contra la nt para comprobar que efectivamente la secuencia alineaba con la bacteria (y efectivamente sigue detectando esa secuencia como la de la bacteria), y otro solo contra la versión 38.p14 del genoma humano(No significant similarity found). Después de esto se confirmó que la última versión del genoma humano 38.p14 ya no tiene este problema.  

#1.1.2. Descarga del Genoma del Fago Phix

Se descargó el assembly GCF_000819615.1 del genoma del Fago Phix de RefSeq (GCF_000819615.1_ViralProj14015_genomic.fna.gz).  

#1.2.Indexar genomas con Bowtie2(phix+human_decont, pig, 3plantas)

```{bash,eval=FALSE}
bowtie2-build genome.fa genome
```

Se genero un único indice resultado de concatenar el genoma humano 38.p14 y el genoma del phago phix GCF_000819615.1.

n 3 indices bowtie2 de genomas de referencia: a) Human Genome 38.p13 con región contaminante enmascarada+ Genoma del Fago Phix; b) Human Genome 38.p13 con región contaminante enmascarada+ Genoma del Fago Phix+Pig Genome para el estudio PRJEB11755_Pig; c) Human Genome 38.p13 con región contaminante enmascarada+ Genoma del Fago Phix+ Genomas de las 3 Plantas presentes en el estudio PRJNA593573_Plant.

#2. Filtrado de lecturas hospedador con Bowtie2 + Samtools

Nos basamos en el siguiente tutorial(https://www.metagenomics.wiki/tools/short-read/remove-host-sequences)






